[workspace]
members = [
  "bridge-ffi",
  "application/interface",
  "application/implement",
  "domain/interface",
  "domain/implement",
  "root",
  "presentation/interface",
  "presentation/implement",
  "state-action",
  "data",
]